### ISSUE TITLE
is it possible to make it synchronous?

### ISSUE THREAD

**Issue by pwong2** [wubzz/pdf-merge#19]
Hi @wubzz I know this is not an issue in pdf-merge, I'm new in node.js and I need your help maybe you already tried on it, I want to know how this method can be synchronous? the file must be merged first before it return the response 200. 

PDFMerge(pdfFiles, { output: filepath, libPath: libPath })

.then(() => {
      res.writeHead(200);
      res.end();
});

thanks in advance

**Comment by wubzz** [comment]
@pwong2 Why do you want to make it synchronous?

Node 8 introduces a nice syntax
```javascript
try {
    const mergedPDFBuffer = await PDFMerge(pdfFiles);

    res.writeHead(200);
    res.end();
} catch(error) {
    //Error handler
}
```

**Comment by wubzz** [comment]
No reply in two days, closing. Reopen if this is still an issue.
