### ISSUE TITLE
process.platform === 'Darwin'

### ISSUE THREAD

**Issue by zimt28** [wubzz/pdf-merge#2]
`pdf-merge` doesn't work on Mac, as the platform `Darwin` contains the string `win`. `pdf-merge` will ask for an absolute path for PDFtk.

**Comment by zimt28** [comment]
Making sure `process.platform`/ `os.platform()` isn't `Darwin` should be enough ([here](https://github.com/wubzz/pdf-merge/blob/master/lib/PdfMerge.js#L57)).

**Comment by wubzz** [comment]
Thanks for reporting this. I've opted to go by `os.type()` instead, since the issue you described would also occur on other platforms.
