### ISSUE TITLE
enable "*.pdf" as filename input

### ISSUE THREAD

**Issue by LockedOnNone** [wubzz/pdf-merge#25]
so I'll write my code like this:
``` javascript
const PDFMerge = require('pdf-merge');
const files = [
	`*.pdf`
];
//Save as new file
PDFMerge(files, {output: `combined.pdf`})
.then((buffer) => {

});
```

so it can support code like this.
```pdftk *.pdf cat output combined.pdf```

**Comment by wubzz** [comment]
This probably worked before #23. To support this we need to make a deviation [here](https://github.com/wubzz/pdf-merge/blob/master/index.js#L55) which makes it so that `*.pdf` continues down the code instead of trying to read the file.
