### ISSUE TITLE
Use same file multiple times

### ISSUE THREAD

**Issue by zimt28** [wubzz/pdf-merge#3]
I'd like to generate a new PDF, which contains another one multiple times. When I provide the PDF multiple times, it will only appear once.

**Comment by zimt28** [comment]
The problem is the use of `union` [here](https://github.com/wubzz/pdf-merge/blob/master/lib/PdfMerge.js#L66).

**Comment by wubzz** [comment]
Thanks for this find. This is something I didn't even consider testing when I built it. Should be fixed now.
