### ISSUE TITLE
How to specify a handle for each file ?

### ISSUE THREAD

**Issue by seme1** [wubzz/pdf-merge#31]
I'm attempting to use the cat option which requires specifying a handle for each file as documented here:
https://www.pdflabs.com/docs/pdftk-man-page/#dest-op-cat

How to specify file handles ? In particular, I'm trying to specify page numbers/ranges for each file to be merged

**Comment by wubzz** [comment]
This is currently not part of this module, but a Pull Request is welcome.

**Comment by seme1** [comment]
This is embarrassing, but I don't know how to "make a pull request". 
I modified the code and it works perfectly fine for me. The code is in this pastebin:
https://pastebin.com/zVB1rC12

Can you please merge it with the current code you have ? I simply added an option called 'catOpt' to specify the page range for each file.

**Comment by wubzz** [comment]
Unfortunately as you can probably tell by how slow I'm responding to issues I am much too busy. You can find out how to make Pull Requests or hope someone else who has time comes by and does this for you.
