### ISSUE TITLE
Deprecated README: pdftk not installable via apt-get

### ISSUE THREAD

**Issue by lkreimann** [wubzz/pdf-merge#35]
We ran into some issues with the pdf-merge (v1.0.1) usage in our application and got this error: 
`pdftk: not found`

This lead us to https://www.npmjs.com/package/pdf-merge where we read the following command: 
> `apt-get install pdftk`

Unfortunately after executing this command, the following messages appeared in the terminal: 

> Package pdftk is not available, but is referred to by another package.

and 

> E: Package 'pdftk' has no installation candidate

Is there any solution to this? E. g. a newer package with a different name? 

I installed [pdftk via snap](https://askubuntu.com/a/1048975/643675) (Version 2.02) on my local machine (Ubuntu 18.04 LTS) and now everything works fine, but I'm afraid a lot more people will run into this error and have problems with pdf-merge as a result.

**Comment by wubzz** [comment]
I don't serve support for installning packages or managing package repositories. You should refer to the link in the README.md:
https://www.pdflabs.com/docs/install-pdftk-on-redhat-or-centos/

**Comment by lkreimann** [comment]
Hi Wubzz,
I just wanted to let you know about this issue because although you don't manage package repositories, you do manage the readme.md file don't you? It makes sense to correct it if the command written in it isn't working.
