### ISSUE TITLE
Encrypt with password

### ISSUE THREAD

**Issue by grachet** [wubzz/pdf-merge#37]
Hi, 
I try to add a password to the final document.
I think it will be in execOption but can you help me ?

` PDFMerge(filesPath, {execOptions : 'password'})
                    .then((buffer) => {
                    })
                    .catch((err) => {
                    })`

**Comment by wubzz** [comment]
`execOptions` is sent directly to PDFtk. You can read their examples here:

https://www.pdflabs.com/docs/pdftk-man-page/
https://www.pdflabs.com/docs/pdftk-cli-examples/
